#!/bin/bash
# Build the AMP packages from the src_repos directory, leaving the packages
# in the packages directory.  This assumes that the CI tool has checked
# out both the amp_bootstrap and the repository/repositories that we want
# to build.

# fail on any error and print current command
set -ex

# Make sure we have the right tools available
# add node v14 to the path
export PATH=/srv/shared/node-v14.19.2-linux-x64/bin:$PATH

# Python is problematic since we need to have the system
# python rather than the one that's in our venv.  Mangle
# the venv part of the path so it doesn't resolve...
export PATH=$(echo $PATH | sed -e s/venv/venv-ignored/)

# add java 11 to the path
export JAVA_HOME=/usr/lib/jvm/java-11
export PATH=$JAVA_HOME/bin:$PATH
echo "PATH: $PATH"
# make sure we're using non-root filesystem for tmp
#export TMP=/srv/services/tmp
#export TMPDIR=$TMP
#export TEMP=$TMP

# set the umask appropriately
umask 022

# Do the actual build...
amp_bootstrap/amp_control.py init
rm -f packages/*
amp_bootstrap/amp_devel.py build

