#!/bin/bash
# Copy the packages in <job_root>/packages to liger's amp_sys-test
# instance.  This can probably be expanded later to use different destinations.
#
# Assumes that the CI user has an authorized ssh key
set -ex

scp packages/*.tar app_amp@liger.dlib.indiana.edu:/srv/services/amp_sys-test-8120/packages
#cp -av packages/*.tar /srv/scratch/packages
